### ISSUE TITLE
Prepare "Organizers" Page

### ISSUE THREAD

**Issue by takatoy** [inlg2024/inlg2024.github.io#7]
ref. https://inlg2023.github.io/organizers.html
After #9

**Comment by toshi835** [comment]
From PC members
- Nguyen Le Minh (Japan Advanced Institute of Science and Technology)
- Daphne Ippolito (Carnegie Mellon University)
- Saad Mahamood (Trivago)

**Comment by takatoy** [comment]
@toshi835 Do you need any help?

**Comment by toshi835** [comment]
I believe I can do it by myself. Try to publish PR this week.  
Thank you for asking!
